"""initial_schema

Revision ID: 1625215c15e4
Revises: 
Create Date: 2026-02-24 14:12:31.096288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '1625215c15e4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otp_codes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_code', sa.String(length=200), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otp_codes_email'), 'otp_codes', ['email'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('google_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_table('courses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('term', sa.String(length=50), nullable=False),
    sa.Column('created_by', sa.String(length=320), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('presentation_types',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('course_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sections',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('course_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'name', name='uq_section_course_name')
    )
    op.create_table('enrollments',
    sa.Column('section_id', sa.String(length=36), nullable=False),
    sa.Column('student_email', sa.String(length=320), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_email'], ['users.email'], ),
    sa.PrimaryKeyConstraint('section_id', 'student_email')
    )
    op.create_table('survey_templates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('presentation_type_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['presentation_type_id'], ['presentation_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teams',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('section_id', sa.String(length=36), nullable=False),
    sa.Column('presentation_type_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['presentation_type_id'], ['presentation_types.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('template_id', sa.String(length=36), nullable=False),
    sa.Column('question_text', sa.String(length=500), nullable=False),
    sa.Column('question_type', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('options', sqlite.JSON(), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['survey_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('section_id', sa.String(length=36), nullable=False),
    sa.Column('presentation_type_id', sa.String(length=36), nullable=False),
    sa.Column('template_snapshot_id', sa.String(length=36), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['presentation_type_id'], ['presentation_types.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.ForeignKeyConstraint(['template_snapshot_id'], ['survey_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team_memberships',
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('student_email', sa.String(length=320), nullable=False),
    sa.ForeignKeyConstraint(['student_email'], ['users.email'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('team_id', 'student_email')
    )
    op.create_table('presentation_grades',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('grade', sa.String(length=10), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('graded_by', sa.String(length=320), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['graded_by'], ['users.email'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_presentation_grades_session_id'), 'presentation_grades', ['session_id'], unique=False)
    op.create_table('session_teams',
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('session_id', 'team_id')
    )
    op.create_table('submissions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('student_email', sa.String(length=320), nullable=False),
    sa.Column('target_team_id', sa.String(length=36), nullable=True),
    sa.Column('target_student_email', sa.String(length=320), nullable=True),
    sa.Column('feedback_type', sa.String(length=20), nullable=False),
    sa.Column('responses', sqlite.JSON(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_late', sa.Boolean(), nullable=False),
    sa.Column('penalty_pct', sa.Integer(), nullable=False),
    sa.Column('withheld', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['student_email'], ['users.email'], ),
    sa.ForeignKeyConstraint(['target_team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'student_email', 'target_team_id', 'target_student_email', 'version', name='uq_submission_version')
    )
    op.create_index(op.f('ix_submissions_session_id'), 'submissions', ['session_id'], unique=False)
    op.create_index(op.f('ix_submissions_student_email'), 'submissions', ['student_email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_submissions_student_email'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_session_id'), table_name='submissions')
    op.drop_table('submissions')
    op.drop_table('session_teams')
    op.drop_index(op.f('ix_presentation_grades_session_id'), table_name='presentation_grades')
    op.drop_table('presentation_grades')
    op.drop_table('team_memberships')
    op.drop_table('sessions')
    op.drop_table('questions')
    op.drop_table('teams')
    op.drop_table('survey_templates')
    op.drop_table('enrollments')
    op.drop_table('sections')
    op.drop_table('presentation_types')
    op.drop_table('courses')
    op.drop_table('users')
    op.drop_index(op.f('ix_otp_codes_email'), table_name='otp_codes')
    op.drop_table('otp_codes')
    # ### end Alembic commands ###
