"""add_admin_instructor_flags_and_instructor_tas

Revision ID: bb8cf6c73062
Revises: 1625215c15e4
Create Date: 2026-02-26 14:50:34.833517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb8cf6c73062'
down_revision: Union[str, Sequence[str], None] = '1625215c15e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instructor_tas',
    sa.Column('instructor_email', sa.String(length=320), nullable=False),
    sa.Column('ta_email', sa.String(length=320), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=320), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.email'], ),
    sa.ForeignKeyConstraint(['instructor_email'], ['users.email'], ),
    sa.ForeignKeyConstraint(['ta_email'], ['users.email'], ),
    sa.PrimaryKeyConstraint('instructor_email', 'ta_email')
    )
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('is_instructor', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###

    # Data migration: seed admin
    op.execute(
        "UPDATE users SET is_admin = true, is_instructor = true "
        "WHERE email = 'alex@aptuslearning.ai'"
    )

    # Data migration: set is_instructor for existing course creators and instructors
    op.execute(
        "UPDATE users SET is_instructor = true "
        "WHERE email IN ("
        "  SELECT DISTINCT created_by FROM courses"
        "  UNION"
        "  SELECT DISTINCT student_email FROM enrollments WHERE role = 'instructor'"
        ")"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_instructor')
    op.drop_column('users', 'is_admin')
    op.drop_table('instructor_tas')
    # ### end Alembic commands ###
